name: Build the documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build docs (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: true  # Ensures venv is inside the project
          installer-parallel: true

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
          sudo apt-get update && sudo apt-get install -y pandoc
          poetry run pip install pandoc  # Ensure it's installed in Poetry's venv

      - name: Debug Poetry Environment
        run: |
          echo "Checking Poetry environment..."
          poetry env info  # Show virtual environment info
          poetry run which sphinx-build  # Check if Sphinx is installed
          poetry run python -m sphinx.cmd.build --version  # Alternative Sphinx call

      - name: Build the documentation with Sphinx
        run: |
          cd docs
          poetry run sphinx-build -b html . _build
